# A few global config settings
API_KEY=''
ORG_ID=''
LINODE_OBJECT_STORAGE_BUCKET_NAME=''
LINODE_OBJECT_STORAGE_ACCESS_KEY=''
LINODE_OBJECT_STORAGE_SECRET_KEY=''
LINODE_OBJECT_STORAGE_HOST_NAME=''
MY_ID=''
PLAYER_LICENSE=''